CREATE TABLE IF NOT EXISTS balloon_counts (
  id SERIAL PRIMARY KEY,
  count INT NOT NULL DEFAULT 0
);

INSERT INTO balloon_counts (count) VALUES (0)
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS messages (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
